# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tree-Node
version:      0.01
version_from: lib/Tree/Node.pm
installdirs:  site
requires:
    base:                          0
    File::Copy:                    0
    File::Spec:                    0
    Test::More:                    0
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
