--- #YAML:1.0
name: Tree-Node
version: 0.06
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Memory-efficient tree nodes in Perl
license: perl
requires:
  base: 0
  perl: 5.6.0
recommends:
  Devel::Leak: 0
  Test::Pod: 1.00
  Test::Pod::Coverage: 0
  Test::Portability::Files: 0
build_requires:
  Test::More: 0
provides:
  Tree::Node:
    file: lib/Tree/Node.pm
    version: 0.06
generated_by: Module::Build version 0.2611
